services:
  # --------------------------------------------------------------------------------
  # BACKEND (Docker)
  # --------------------------------------------------------------------------------
  - type: web
    name: BrainScript-backend
    env: docker
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
      - key: SERVER_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PYTHON_BIN
        value: python3
      - key: TRANSCRIPT_LANGS
        value: en,en-US,en-GB,en-IN,hi
      - key: GEMINI_API_KEY_QUIZ
        sync: false
      - key: SUMMARY_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
